#!/usr/bin/env node
// Generates Codex and Gemini CLI agent files from the Claude Code agent definitions.
// The Claude files in plugins/<plugin>/agents/ are the source of truth; the output is committed
// under plugins/<plugin>/platforms/ so users of other tools can copy it without running this.
//
//   node scripts/gen-agents.mjs            write the generated files
//   node scripts/gen-agents.mjs --check    exit 1 if any generated file is missing or stale

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const READ_ONLY_TOOLS = new Set(['Read', 'Grep', 'Glob']);

function parse(file) {
  const text = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`${file}: no frontmatter`);
  const meta = {};
  let listKey = null;
  for (const line of m[1].split('\n')) {
    const item = line.match(/^\s+-\s+(.*)$/);
    if (item && listKey) { meta[listKey].push(item[1].trim()); continue; }
    const kv = line.match(/^([\w-]+):\s*(.*)$/);
    if (!kv) continue;
    listKey = null;
    if (kv[2] === '') { meta[kv[1]] = []; listKey = kv[1]; } else meta[kv[1]] = kv[2].trim();
  }
  return { meta, body: m[2].trim() };
}

function portableBody({ meta, body }, platform) {
  const lines = [];
  for (const skill of meta.skills ?? []) {
    lines.push(`Before starting, read the \`${skill}\` skill's SKILL.md and follow it. It is in the skills installed for this tool (for Codex, \`.agents/skills/${skill}/\`; for Gemini, wherever the pack's skills were installed).`);
  }
  const tools = (meta.tools ?? '').split(',').map((t) => t.trim()).filter(Boolean);
  const readOnly = tools.length > 0 && tools.every((t) => READ_ONLY_TOOLS.has(t));
  if (readOnly && platform === 'gemini') lines.push('You are read-only: read and search files, never edit, write, or run commands that change anything.');
  if (platform === 'gemini') lines.push('You cannot start other agents here; wherever these instructions say to ask a subagent, decide yourself by the same rules.');
  const preface = lines.length ? lines.join('\n\n') + '\n\n' : '';
  // Claude's preloaded skills become a read-first instruction, so drop the "preloaded" wording.
  return { text: preface + body.replace(/the preloaded `([\w-]+)` skill/g, 'the `$1` skill'), readOnly };
}

const tomlString = (s) => '"""\n' + s.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"') + '\n"""';
const tomlLine = (s) => JSON.stringify(s);

function codex(agent) {
  const { meta } = agent;
  const { text, readOnly } = portableBody(agent, 'codex');
  const out = [
    '# Generated by scripts/gen-agents.mjs from the Claude Code agent file. Edit that file, not this one.',
    `name = ${tomlLine(meta.name)}`,
    `description = ${tomlLine(meta.description)}`,
  ];
  if (readOnly) out.push('sandbox_mode = "read-only"');
  out.push(`developer_instructions = ${tomlString(text)}`);
  return out.join('\n') + '\n';
}

function gemini(agent) {
  const { meta } = agent;
  const { text } = portableBody(agent, 'gemini');
  return [
    '---',
    `name: ${meta.name}`,
    `description: ${JSON.stringify(meta.description)}`,
    '---',
    '<!-- Generated by scripts/gen-agents.mjs from the Claude Code agent file. Edit that file, not this one. -->',
    '',
    text,
    '',
  ].join('\n');
}

let stale = 0;
function emit(path, content) {
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) return;
  if (CHECK) { console.error(`stale: ${path}`); stale++; return; }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${path}`);
}

for (const plugin of readdirSync(join(ROOT, 'plugins'))) {
  const dir = join(ROOT, 'plugins', plugin, 'agents');
  if (!existsSync(dir)) continue;
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.md'))) {
    const agent = parse(join(dir, file));
    const name = agent.meta.name ?? basename(file, '.md');
    const out = join(ROOT, 'plugins', plugin, 'platforms');
    emit(join(out, 'codex', 'agents', `${name}.toml`), codex(agent));
    emit(join(out, 'gemini', 'agents', `${name}.md`), gemini(agent));
  }
}
if (stale) process.exit(1);
