#!/usr/bin/env node
// Generates one reference page per skill under docs/skills/ from each skill's SKILL.md, plus an index.
// SKILL.md is the source of truth; edit it and re-run this script instead of editing the pages.
//
//   node scripts/gen-docs.mjs            write the generated pages
//   node scripts/gen-docs.mjs --check    exit 1 if any page is missing, stale, or orphaned

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const OUT = join(ROOT, 'docs', 'skills');
const HEADER = '<!-- Generated by scripts/gen-docs.mjs from SKILL.md. Edit the skill, not this page. -->';

function parse(file) {
  const text = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`${file}: no frontmatter`);
  const meta = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^([\w-]+):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].trim().replace(/^"(.*)"$/, '$1');
  }
  return { meta, body: m[2] };
}

// The skill's handoff: the last line that starts with a `next:` handoff, outside code fences.
function handoff(body) {
  let fenced = false;
  let found = null;
  for (const line of body.split('\n')) {
    if (line.startsWith('```')) { fenced = !fenced; continue; }
    if (fenced) continue;
    const m = line.match(/^(?:Handoff\s*[—-]\s*)?`next:`\s*(.*)$/);
    if (m) found = m[1].trim();
  }
  return found;
}

// Every project settings path the skill names, in order of first mention.
function settingsPaths(body) {
  return [...new Set(body.match(/\.claude\/shipyard\/[\w./<>-]+\.md/g) ?? [])];
}

function page(plugin, skill, { meta, body }) {
  const skillDir = `../../plugins/${plugin}/skills/${skill}`;
  const userOnly = meta['disable-model-invocation'] === 'true';
  const next = handoff(body);
  const settings = settingsPaths(body);
  const sources = join(ROOT, 'plugins', plugin, 'docs', 'sources', `${skill}.md`);
  const rows = [
    ['Who starts it', userOnly
      ? `You, by name: \`/${plugin}:${skill}\` in Claude Code, or ask for it in other agents. The agent doesn't start it on its own.`
      : `You or the agent. You can ask for it by name (\`/${plugin}:${skill}\` in Claude Code); the agent also starts it when the request matches the description.`],
    ['Arguments', meta['argument-hint'] ? `\`${meta['argument-hint']}\`` : 'none'],
    ['Project settings', settings.length ? settings.map((p) => `\`${p}\``).join(', ') : 'none'],
    ['Settings fields', existsSync(join(ROOT, 'plugins', plugin, 'skills', skill, 'references', 'overlay-example.md'))
      ? `[overlay-example.md](${skillDir}/references/overlay-example.md)` : 'none'],
    ['Hands off to', next ?? 'nothing: this skill has no `next:` line'],
    ['Source', `[SKILL.md](${skillDir}/SKILL.md)` + (existsSync(sources) ? `; where its rules came from: [docs/sources/${skill}.md](../../plugins/${plugin}/docs/sources/${skill}.md)` : '')],
  ];
  if (meta['allowed-tools']) rows.splice(2, 0, ['Allowed tools', meta['allowed-tools']]);
  return [
    HEADER,
    '',
    `# ${meta.name ?? skill}`,
    '',
    meta.description ?? '',
    '',
    '| | |',
    '|---|---|',
    ...rows.map(([k, v]) => `| ${k} | ${v.replace(/\|/g, '\\|')} |`),
    '',
  ].join('\n');
}

let stale = 0;
const expected = new Set();
function emit(path, content) {
  expected.add(basename(path));
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) return;
  if (CHECK) { console.error(`stale: ${path}`); stale++; return; }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${path}`);
}

const index = [];
for (const plugin of readdirSync(join(ROOT, 'plugins'))) {
  const dir = join(ROOT, 'plugins', plugin, 'skills');
  if (!existsSync(dir)) continue;
  for (const skill of readdirSync(dir).sort()) {
    const file = join(dir, skill, 'SKILL.md');
    if (!existsSync(file)) continue;
    const parsed = parse(file);
    emit(join(OUT, `${skill}.md`), page(plugin, skill, parsed));
    const userOnly = parsed.meta['disable-model-invocation'] === 'true';
    index.push(`| [${skill}](${skill}.md) | ${userOnly ? 'you' : 'you or the agent'} | ${parsed.meta['argument-hint'] ? `\`${parsed.meta['argument-hint'].replace(/\|/g, '\\|')}\`` : ''} |`);
  }
}
emit(join(OUT, 'README.md'), [
  HEADER,
  '',
  '# skill reference',
  '',
  'One page per skill, generated from its `SKILL.md`.',
  '',
  '| Skill | Who starts it | Arguments |',
  '|---|---|---|',
  ...index,
  '',
].join('\n'));

if (existsSync(OUT)) {
  for (const f of readdirSync(OUT)) {
    if (f.endsWith('.md') && !expected.has(f)) { console.error(`orphaned: ${join(OUT, f)} (no matching skill)`); stale++; }
  }
}
if (stale) process.exit(1);
